name: NTR
description: 'Nutrion Tracker Recipes'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.5
  flutter_dotenv: ^5.2.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  image_picker: ^1.1.2
  pocketbase: ^0.22.0
  shared_preferences: ^2.5.2
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/default/
    - assets/fonts/
    - assets/food-types/
    - assets/logos/
    - .env

  fonts:
    - family: Calibri
      fonts:
        - asset: assets/fonts/calibri-regular.ttf
        - asset: assets/fonts/calibri-bold.ttf
          weight: 800

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/app-icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets\logos\app-splash.png
  android_12:
    image: assets\logos\app-splash.png
    color: "#ffffff"

  fullscreen: true
  android: true
  ios: true